# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5061c4711cb942ce2410b250cf5bc42a040329160b149b4129ba87bead6d0c16dc9748d156f5bfbd5469cbed19831005a44b5e131570608f8a8a246d5fec9242

test:
  secret_key_base: 67fed79244cbdab830ff53822371959e0d936ce8d428ec3252d06ed0fa886b75535d1ff9398d6e22b0742fd5a3f44b548d9c4980a3592bf64de63564317f0729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
